name: Deploy to heroku.

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build, Push and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@1.3.3
        with:
          
          email: caoduonghien@gmail.com

          heroku_api_key: 3f8e8324-a9d2-4590-8a84-fb83268d6e44

          heroku_app_name: test-hien

          dockerfile_directory: ./

          dockerfile_name: Dockerfile

          dockerfile_options: "--no-cache"
          
          process_type: web